### ISSUE TITLE
newWritebatch() not accessible in Swift.

### ISSUE THREAD

**Issue by chakrit** [matehat/Objective-LevelDB#19]
I think this might be because the method has the word `new` as a prefix.

Is there anyway to work around this?

**Comment by chakrit** [comment]
Turns out this was my mistake. If anyone else comes across this, don't forget to also includes `LDBWritebatch.h` in your Swift bridging header file:

```
#import <LevelDB.h>
#import <LDBWriteBatch.h>
```

**Comment by matehat** [comment]
:+1:
