### ISSUE TITLE
Crash in deleteDatabaseFromDisk method

### ISSUE THREAD

**Issue by matthewyan** [matehat/Objective-LevelDB#35]
The "path" property may release, May be should retain it in init method

I changed the init function:
![image](https://cloud.githubusercontent.com/assets/8739896/15418250/686f1176-1e90-11e6-8496-bff7bd92a834.png)

It's works fine

**Comment by dsanghan** [comment]
^noticed the same thing

**Comment by cntrump** [comment]
replace retain with copy

`/**
 The path of the database on disk
 */
@property (nonatomic, retain) NSString *path;

/**
 The name of the database.
 */
@property (nonatomic, retain) NSString *name;`

`/**
 The path of the database on disk
 */
@property (nonatomic, copy) NSString *path;

/**
 The name of the database.
 */
@property (nonatomic, copy) NSString *name;`
